# Generated by Django 5.2.11 on 2026-02-26 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('asset_id', models.CharField(blank=True, max_length=100)),
                ('resolution', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('workbench', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='workshops.workbench')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='workshops.workshop')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-urgency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_tags',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('time_spent_min', models.PositiveIntegerField(default=0, help_text='Time spent in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workshop', 'status'], name='tickets_worksho_7e336e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workshop', 'urgency'], name='tickets_worksho_069f76_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['workshop', 'assignee'], name='tickets_worksho_83bc25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettag',
            unique_together={('ticket', 'name')},
        ),
    ]
