# Generated by Django 5.2.13 on 2026-04-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
